FROM node:20-bookworm-slim

RUN apt-get update \
  && apt-get install -y --no-install-recommends git python3 make g++ ca-certificates \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN REVISION="$(git rev-parse --short=12 HEAD 2>/dev/null || true)" \
  && printf '%s\n' "${REVISION:-unknown}" > .build-revision
RUN npm run build
RUN npm prune --omit=dev

ENV NODE_ENV=production
ENV PORT=7860
ENV ENABLE_TELEGRAM_BOT=true
ENV TELEGRAM_USE_WEBHOOK=false
ENV ENABLE_EXECUTOR_WORKER=true
ENV ENABLE_MONITOR_WORKER=true
ENV ENABLE_SNIPER_WORKER=true
ENV ENABLE_METRICS_SNAPSHOT_LOGS=false
ENV SNIPER_ENABLE_DEXSCREENER=false
ENV SNIPER_WARMUP_MS=12000
ENV SNIPER_MAX_TRACKED_TOKENS=80
ENV SNIPER_LOG_QUEUE_MAX=15
ENV SNIPER_LOG_PROCESS_INTERVAL_MS=3000
ENV SNIPER_CREATE_PROCESS_INTERVAL_MS=15000
ENV RPC_HEALTH_CACHE_MS=30000
ENV RPC_ENDPOINT_COOLDOWN_MS=180000
ENV RPC_ERROR_LOG_COOLDOWN_MS=60000
ENV SNIPER_MIN_INITIAL_LIQUIDITY_SOL=1
ENV SNIPER_MIN_UNIQUE_BUYER_RATIO=0.3
ENV SNIPER_MAX_SUSPICIOUS_WALLETS=3
ENV SNIPER_MAX_CURVE_PROGRESS_PCT=75
ENV SNIPER_MAX_DEV_WALLET_PCT=15

EXPOSE 7860

CMD ["sh", "-c", "node dist/scripts/migrate.js && node --max-old-space-size=8192 dist/allInOne.js"]
